// Licensed to The Moov Authors under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. The Moov Authors licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Generated on 2025-01-23T12:37:49Z by adam, any modifications will be overwritten
package iso3166

var countryCodes = map[string][]string{
	"AF": []string{"Afghanistan"},
	"AL": []string{"Albania"},
	"DZ": []string{"Algeria"},
	"AS": []string{"American Samoa"},
	"AD": []string{"Andorra"},
	"AO": []string{"Angola"},
	"AI": []string{"Anguilla"},
	"AQ": []string{"Antarctica"},
	"AG": []string{"Antigua and Barbuda"},
	"AR": []string{"Argentina"},
	"AM": []string{"Armenia"},
	"AW": []string{"Aruba"},
	"AU": []string{"Australia"},
	"AT": []string{"Austria"},
	"AZ": []string{"Azerbaijan"},
	"BS": []string{"Bahamas"},
	"BH": []string{"Bahrain"},
	"BD": []string{"Bangladesh"},
	"BB": []string{"Barbados"},
	"BY": []string{"Belarus"},
	"BE": []string{"Belgium"},
	"BZ": []string{"Belize"},
	"BJ": []string{"Benin"},
	"BM": []string{"Bermuda"},
	"BT": []string{"Bhutan"},
	"BO": []string{"Bolivia, Plurinational State of"},
	"BQ": []string{"Bonaire, Sint Eustatius and Saba"},
	"BA": []string{"Bosnia and Herzegovina"},
	"BW": []string{"Botswana"},
	"BV": []string{"Bouvet Island"},
	"BR": []string{"Brazil"},
	"IO": []string{"British Indian Ocean Territory"},
	"BN": []string{"Brunei Darussalam"},
	"BG": []string{"Bulgaria"},
	"BF": []string{"Burkina Faso"},
	"BI": []string{"Burundi"},
	"CV": []string{"Cabo Verde"},
	"KH": []string{"Cambodia"},
	"CM": []string{"Cameroon"},
	"CA": []string{"Canada"},
	"KY": []string{"Cayman Islands"},
	"CF": []string{"Central African Republic"},
	"TD": []string{"Chad"},
	"CL": []string{"Chile"},
	"CN": []string{"China"},
	"CX": []string{"Christmas Island"},
	"CC": []string{"Cocos (Keeling) Islands"},
	"CO": []string{"Colombia"},
	"KM": []string{"Comoros"},
	"CG": []string{"Congo"},
	"CD": []string{"Congo, Democratic Republic of the"},
	"CK": []string{"Cook Islands"},
	"CR": []string{"Costa Rica"},
	"HR": []string{"Croatia"},
	"CU": []string{"Cuba"},
	"CW": []string{"Curaçao"},
	"CY": []string{"Cyprus"},
	"CZ": []string{"Czechia"},
	"CI": []string{"Côte d'Ivoire"},
	"DK": []string{"Denmark"},
	"DJ": []string{"Djibouti"},
	"DM": []string{"Dominica"},
	"DO": []string{"Dominican Republic"},
	"EC": []string{"Ecuador"},
	"EG": []string{"Egypt"},
	"SV": []string{"El Salvador"},
	"GQ": []string{"Equatorial Guinea"},
	"ER": []string{"Eritrea"},
	"EE": []string{"Estonia"},
	"SZ": []string{"Eswatini"},
	"ET": []string{"Ethiopia"},
	"FK": []string{"Falkland Islands (Malvinas)"},
	"FO": []string{"Faroe Islands"},
	"FJ": []string{"Fiji"},
	"FI": []string{"Finland"},
	"FR": []string{"France"},
	"GF": []string{"French Guiana"},
	"PF": []string{"French Polynesia"},
	"TF": []string{"French Southern Territories"},
	"GA": []string{"Gabon"},
	"GM": []string{"Gambia"},
	"GE": []string{"Georgia"},
	"DE": []string{"Germany"},
	"GH": []string{"Ghana"},
	"GI": []string{"Gibraltar"},
	"GR": []string{"Greece"},
	"GL": []string{"Greenland"},
	"GD": []string{"Grenada"},
	"GP": []string{"Guadeloupe"},
	"GU": []string{"Guam"},
	"GT": []string{"Guatemala"},
	"GG": []string{"Guernsey"},
	"GN": []string{"Guinea"},
	"GW": []string{"Guinea-Bissau"},
	"GY": []string{"Guyana"},
	"HT": []string{"Haiti"},
	"HM": []string{"Heard Island and McDonald Islands"},
	"VA": []string{"Holy See"},
	"HN": []string{"Honduras"},
	"HK": []string{"Hong Kong"},
	"HU": []string{"Hungary"},
	"IS": []string{"Iceland"},
	"IN": []string{"India"},
	"ID": []string{"Indonesia"},
	"IR": []string{"Iran, Islamic Republic of"},
	"IQ": []string{"Iraq"},
	"IE": []string{"Ireland"},
	"IM": []string{"Isle of Man"},
	"IL": []string{"Israel"},
	"IT": []string{"Italy"},
	"JM": []string{"Jamaica"},
	"JP": []string{"Japan"},
	"JE": []string{"Jersey"},
	"JO": []string{"Jordan"},
	"KZ": []string{"Kazakhstan"},
	"KE": []string{"Kenya"},
	"KI": []string{"Kiribati"},
	"KP": []string{"Korea, Democratic People's Republic of"},
	"KR": []string{"Korea, Republic of"},
	"KW": []string{"Kuwait"},
	"KG": []string{"Kyrgyzstan"},
	"LA": []string{"Lao People's Democratic Republic"},
	"LV": []string{"Latvia"},
	"LB": []string{"Lebanon"},
	"LS": []string{"Lesotho"},
	"LR": []string{"Liberia"},
	"LY": []string{"Libya"},
	"LI": []string{"Liechtenstein"},
	"LT": []string{"Lithuania"},
	"LU": []string{"Luxembourg"},
	"MO": []string{"Macao"},
	"MG": []string{"Madagascar"},
	"MW": []string{"Malawi"},
	"MY": []string{"Malaysia"},
	"MV": []string{"Maldives"},
	"ML": []string{"Mali"},
	"MT": []string{"Malta"},
	"MH": []string{"Marshall Islands"},
	"MQ": []string{"Martinique"},
	"MR": []string{"Mauritania"},
	"MU": []string{"Mauritius"},
	"YT": []string{"Mayotte"},
	"MX": []string{"Mexico"},
	"FM": []string{"Micronesia, Federated States of"},
	"MD": []string{"Moldova, Republic of"},
	"MC": []string{"Monaco"},
	"MN": []string{"Mongolia"},
	"ME": []string{"Montenegro"},
	"MS": []string{"Montserrat"},
	"MA": []string{"Morocco"},
	"MZ": []string{"Mozambique"},
	"MM": []string{"Myanmar"},
	"NA": []string{"Namibia"},
	"NR": []string{"Nauru"},
	"NP": []string{"Nepal"},
	"NL": []string{"Netherlands"},
	"NC": []string{"New Caledonia"},
	"NZ": []string{"New Zealand"},
	"NI": []string{"Nicaragua"},
	"NE": []string{"Niger"},
	"NG": []string{"Nigeria"},
	"NU": []string{"Niue"},
	"NF": []string{"Norfolk Island"},
	"MK": []string{"North Macedonia"},
	"MP": []string{"Northern Mariana Islands"},
	"NO": []string{"Norway"},
	"OM": []string{"Oman"},
	"PK": []string{"Pakistan"},
	"PW": []string{"Palau"},
	"PS": []string{"Palestine, State of"},
	"PA": []string{"Panama"},
	"PG": []string{"Papua New Guinea"},
	"PY": []string{"Paraguay"},
	"PE": []string{"Peru"},
	"PH": []string{"Philippines"},
	"PN": []string{"Pitcairn"},
	"PL": []string{"Poland"},
	"PT": []string{"Portugal"},
	"PR": []string{"Puerto Rico"},
	"QA": []string{"Qatar"},
	"RO": []string{"Romania"},
	"RU": []string{"Russian Federation"},
	"RW": []string{"Rwanda"},
	"RE": []string{"Réunion"},
	"BL": []string{"Saint Barthélemy"},
	"SH": []string{"Saint Helena, Ascension and Tristan da Cunha"},
	"KN": []string{"Saint Kitts and Nevis"},
	"LC": []string{"Saint Lucia"},
	"MF": []string{"Saint Martin, (French part)"},
	"PM": []string{"Saint Pierre and Miquelon"},
	"VC": []string{"Saint Vincent and the Grenadines"},
	"WS": []string{"Samoa"},
	"SM": []string{"San Marino"},
	"ST": []string{"Sao Tome and Principe"},
	"SA": []string{"Saudi Arabia"},
	"SN": []string{"Senegal"},
	"RS": []string{"Serbia"},
	"SC": []string{"Seychelles"},
	"SL": []string{"Sierra Leone"},
	"SG": []string{"Singapore"},
	"SX": []string{"Sint Maarten, (Dutch part)"},
	"SK": []string{"Slovakia"},
	"SI": []string{"Slovenia"},
	"SB": []string{"Solomon Islands"},
	"SO": []string{"Somalia"},
	"ZA": []string{"South Africa"},
	"GS": []string{"South Georgia and the South Sandwich Islands"},
	"SS": []string{"South Sudan"},
	"ES": []string{"Spain"},
	"LK": []string{"Sri Lanka"},
	"SD": []string{"Sudan"},
	"SR": []string{"Suriname"},
	"SJ": []string{"Svalbard and Jan Mayen"},
	"SE": []string{"Sweden"},
	"CH": []string{"Switzerland"},
	"SY": []string{"Syrian Arab Republic"},
	"TW": []string{"Taiwan, Province of China"},
	"TJ": []string{"Tajikistan"},
	"TZ": []string{"Tanzania, United Republic of"},
	"TH": []string{"Thailand"},
	"TL": []string{"Timor-Leste"},
	"TG": []string{"Togo"},
	"TK": []string{"Tokelau"},
	"TO": []string{"Tonga"},
	"TT": []string{"Trinidad and Tobago"},
	"TN": []string{"Tunisia"},
	"TM": []string{"Turkmenistan"},
	"TC": []string{"Turks and Caicos Islands"},
	"TV": []string{"Tuvalu"},
	"TR": []string{"Türkiye"},
	"UG": []string{"Uganda"},
	"UA": []string{"Ukraine"},
	"AE": []string{"United Arab Emirates"},
	"GB": []string{"United Kingdom of Great Britain and Northern Ireland", "United Kingdom", "England"},
	"UM": []string{"United States Minor Outlying Islands"},
	"US": []string{"United States of America", "USA", "United States"},
	"UY": []string{"Uruguay"},
	"UZ": []string{"Uzbekistan"},
	"VU": []string{"Vanuatu"},
	"VE": []string{"Venezuela, Bolivarian Republic of"},
	"VN": []string{"Viet Nam"},
	"VG": []string{"Virgin Islands, British"},
	"VI": []string{"Virgin Islands, U.S."},
	"WF": []string{"Wallis and Futuna"},
	"EH": []string{"Western Sahara"},
	"YE": []string{"Yemen"},
	"ZM": []string{"Zambia"},
	"ZW": []string{"Zimbabwe"},
	"AX": []string{"Åland Islands"},
}
