// Licensed to The Moov Authors under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. The Moov Authors licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package iso3166

var alpha2Codes = map[string][]string{
	"AD": {"Andorra"},
	"AE": {"United Arab Emirates", "UAE"},
	"AF": {"Afghanistan"},
	"AG": {"Antigua and Barbuda"},
	"AI": {"Anguilla"},
	"AL": {"Albania"},
	"AM": {"Armenia"},
	"AO": {"Angola"},
	"AQ": {"Antarctica"},
	"AR": {"Argentina"},
	"AS": {"American Samoa"},
	"AT": {"Austria"},
	"AU": {"Australia"},
	"AW": {"Aruba"},
	"AX": {"Åland Islands", "Aland Islands"},
	"AZ": {"Azerbaijan"},
	"BA": {"Bosnia and Herzegovina"},
	"BB": {"Barbados"},
	"BD": {"Bangladesh"},
	"BE": {"Belgium"},
	"BF": {"Burkina Faso"},
	"BG": {"Bulgaria"},
	"BH": {"Bahrain"},
	"BI": {"Burundi"},
	"BJ": {"Benin"},
	"BL": {"Saint Barthélemy", "Saint Barthelemy"},
	"BM": {"Bermuda"},
	"BN": {"Brunei Darussalam", "Brunei"},
	"BO": {"Bolivia, Plurinational State of"},
	"BQ": {"Bonaire, Sint Eustatius and Saba", "Bonaire", "Sint Eustatius and Saba", "BES Islands"},
	"BR": {"Brazil"},
	"BS": {"Bahamas"},
	"BT": {"Bhutan"},
	"BV": {"Bouvet Island"},
	"BW": {"Botswana"},
	"BY": {"Belarus"},
	"BZ": {"Belize"},
	"CA": {"Canada"},
	"CC": {"Cocos (Keeling) Islands", "Cocos Islands", "Cocos Keeling Islands"},
	"CD": {"Congo, Democratic Republic of the", "Democratic Republic of the Congo", "DRC", "DR Congo", "Congo Democratic Republic"},
	"CF": {"Central African Republic", "CAR"},
	"CG": {"Congo", "Republic of Congo"},
	"CH": {"Switzerland"},
	"CI": {"Côte d'Ivoire", "Ivory Coast"},
	"CK": {"Cook Islands"},
	"CL": {"Chile"},
	"CM": {"Cameroon"},
	"CN": {"China", "Peoples Republic of China"},
	"CO": {"Colombia"},
	"CR": {"Costa Rica"},
	"CU": {"Cuba"},
	"CV": {"Cabo Verde", "Cape Verde"},
	"CW": {"Curaçao"},
	"CX": {"Christmas Island"},
	"CY": {"Cyprus"},
	"CZ": {"Czechia", "Czech Republic"},
	"DE": {"Germany"},
	"DJ": {"Djibouti"},
	"DK": {"Denmark"},
	"DM": {"Dominica"},
	"DO": {"Dominican Republic"},
	"DZ": {"Algeria"},
	"EC": {"Ecuador"},
	"EE": {"Estonia"},
	"EG": {"Egypt"},
	"EH": {"Western Sahara"},
	"ER": {"Eritrea"},
	"ES": {"Spain"},
	"ET": {"Ethiopia"},
	"FI": {"Finland"},
	"FJ": {"Fiji"},
	"FK": {"Falkland Islands (Malvinas)", "Falkland Islands", "Malvinas"},
	"FM": {"Micronesia, Federated States of", "Micronesia", "FSM", "Micronesia Federated States"},
	"FO": {"Faroe Islands"},
	"FR": {"France"},
	"GA": {"Gabon"},
	"GB": {"United Kingdom of Great Britain and Northern Ireland", "United Kingdom", "England", "Great Britain", "Britan"},
	"GD": {"Grenada"},
	"GE": {"Georgia"},
	"GF": {"French Guiana"},
	"GG": {"Guernsey"},
	"GH": {"Ghana"},
	"GI": {"Gibraltar"},
	"GL": {"Greenland"},
	"GM": {"Gambia"},
	"GN": {"Guinea"},
	"GP": {"Guadeloupe"},
	"GQ": {"Equatorial Guinea"},
	"GR": {"Greece"},
	"GS": {"South Georgia and the South Sandwich Islands"},
	"GT": {"Guatemala"},
	"GU": {"Guam"},
	"GW": {"Guinea-Bissau", "Guinea Bissau"},
	"GY": {"Guyana"},
	"HK": {"Hong Kong"},
	"HM": {"Heard Island and McDonald Islands"},
	"HN": {"Honduras"},
	"HR": {"Croatia"},
	"HT": {"Haiti"},
	"HU": {"Hungary"},
	"ID": {"Indonesia"},
	"IE": {"Ireland", "Eire"},
	"IL": {"Israel"},
	"IM": {"Isle of Man"},
	"IN": {"India"},
	"IO": {"British Indian Ocean Territory"},
	"IQ": {"Iraq"},
	"IR": {"Iran, Islamic Republic of", "Iran", "Iran Islamic Republic", "Persia"},
	"IS": {"Iceland"},
	"IT": {"Italy"},
	"JE": {"Jersey"},
	"JM": {"Jamaica"},
	"JO": {"Jordan"},
	"JP": {"Japan"},
	"KE": {"Kenya"},
	"KG": {"Kyrgyzstan"},
	"KH": {"Cambodia"},
	"KI": {"Kiribati"},
	"KM": {"Comoros"},
	"KN": {"Saint Kitts and Nevis"},
	"KP": {"Korea, Democratic People's Republic of", "North Korea", "Korea Democratic Peoples Republic", "DPRK"},
	"KR": {"Korea, Republic of", "South Korea", "Korea Republic", "Republic of Korea"},
	"KW": {"Kuwait"},
	"KY": {"Cayman Islands"},
	"KZ": {"Kazakhstan"},
	"LA": {"Lao People's Democratic Republic", "Laos", "Lao Peoples Democratic Republic"},
	"LB": {"Lebanon"},
	"LC": {"Saint Lucia"},
	"LI": {"Liechtenstein"},
	"LK": {"Sri Lanka", "Ceylon"},
	"LR": {"Liberia"},
	"LS": {"Lesotho"},
	"LT": {"Lithuania"},
	"LU": {"Luxembourg"},
	"LV": {"Latvia"},
	"LY": {"Libya"},
	"MA": {"Morocco"},
	"MC": {"Monaco"},
	"MD": {"Moldova, Republic of", "Moldova", "Moldova Republic"},
	"ME": {"Montenegro"},
	"MF": {"Saint Martin, (French part)", "Saint Martin French", "Saint Martin"},
	"MG": {"Madagascar"},
	"MH": {"Marshall Islands"},
	"MK": {"North Macedonia", "Macedonia"},
	"ML": {"Mali"},
	"MM": {"Myanmar", "Burma"},
	"MN": {"Mongolia"},
	"MO": {"Macao", "Macau"},
	"MP": {"Northern Mariana Islands"},
	"MQ": {"Martinique"},
	"MR": {"Mauritania"},
	"MS": {"Montserrat"},
	"MT": {"Malta"},
	"MU": {"Mauritius"},
	"MV": {"Maldives"},
	"MW": {"Malawi"},
	"MX": {"Mexico"},
	"MY": {"Malaysia"},
	"MZ": {"Mozambique"},
	"NA": {"Namibia"},
	"NC": {"New Caledonia"},
	"NE": {"Niger"},
	"NF": {"Norfolk Island"},
	"NG": {"Nigeria"},
	"NI": {"Nicaragua"},
	"NL": {"Netherlands", "Holland"},
	"NO": {"Norway"},
	"NP": {"Nepal"},
	"NR": {"Nauru"},
	"NU": {"Niue"},
	"NZ": {"New Zealand", "Aotearoa"},
	"OM": {"Oman"},
	"PA": {"Panama"},
	"PE": {"Peru"},
	"PF": {"French Polynesia"},
	"PG": {"Papua New Guinea", "PNG"},
	"PH": {"Philippines"},
	"PK": {"Pakistan"},
	"PL": {"Poland"},
	"PM": {"Saint Pierre and Miquelon"},
	"PN": {"Pitcairn"},
	"PR": {"Puerto Rico"},
	"PS": {"Palestine, State of", "Palestine", "State of Palestine"},
	"PT": {"Portugal"},
	"PW": {"Palau"},
	"PY": {"Paraguay"},
	"QA": {"Qatar"},
	"RE": {"Réunion", "Reunion"},
	"RO": {"Romania"},
	"RS": {"Serbia"},
	"RU": {"Russian Federation", "Russia", "RF"},
	"RW": {"Rwanda"},
	"SA": {"Saudi Arabia", "KSA"},
	"SB": {"Solomon Islands"},
	"SC": {"Seychelles"},
	"SD": {"Sudan"},
	"SE": {"Sweden"},
	"SG": {"Singapore"},
	"SH": {"Saint Helena, Ascension and Tristan da Cunha", "Saint Helena Ascension and Tristan da Cunha", "Saint Helena"},
	"SI": {"Slovenia"},
	"SJ": {"Svalbard and Jan Mayen"},
	"SK": {"Slovakia"},
	"SL": {"Sierra Leone"},
	"SM": {"San Marino"},
	"SN": {"Senegal"},
	"SO": {"Somalia"},
	"SR": {"Suriname"},
	"SS": {"South Sudan"},
	"ST": {"Sao Tome and Principe"},
	"SV": {"El Salvador"},
	"SX": {"Sint Maarten, (Dutch part)", "Sint Maarten Dutch"},
	"SY": {"Syrian Arab Republic", "Syria", "Syrian Arab Republic"},
	"SZ": {"Eswatini", "Swaziland"},
	"TC": {"Turks and Caicos Islands"},
	"TD": {"Chad"},
	"TF": {"French Southern Territories"},
	"TG": {"Togo"},
	"TH": {"Thailand", "Siam"},
	"TJ": {"Tajikistan"},
	"TK": {"Tokelau"},
	"TL": {"Timor-Leste", "Timor Leste", "East Timor"},
	"TM": {"Turkmenistan"},
	"TN": {"Tunisia"},
	"TO": {"Tonga"},
	"TR": {"Türkiye", "Turkiye", "Turkey"},
	"TT": {"Trinidad and Tobago"},
	"TV": {"Tuvalu"},
	"TW": {"Taiwan, Province of China", "Taiwan", "Taiwan Province of China"},
	"TZ": {"Tanzania, United Republic of", "Tanzania", "Tanzania United Republic"},
	"UA": {"Ukraine"},
	"UG": {"Uganda"},
	"UM": {"United States Minor Outlying Islands"},
	"US": {"United States of America", "United States", "USA", "US", "America"},
	"UY": {"Uruguay"},
	"UZ": {"Uzbekistan"},
	"VA": {"Holy See", "Vatican", "Vatican City"},
	"VC": {"Saint Vincent and the Grenadines"},
	"VE": {"Venezuela, Bolivarian Republic of", "Venezuela", "Venezuela Bolivarian Republic"},
	"VG": {"Virgin Islands, British", "British Virgin Islands", "Virgin Islands British"},
	"VI": {"Virgin Islands, U.S.", "US Virgin Islands", "Virgin Islands US"},
	"VN": {"Viet Nam", "Vietnam"},
	"VU": {"Vanuatu"},
	"WF": {"Wallis and Futuna"},
	"WS": {"Samoa"},
	"YE": {"Yemen"},
	"YT": {"Mayotte"},
	"ZA": {"South Africa"},
	"ZM": {"Zambia"},
	"ZW": {"Zimbabwe"},
}
