// Licensed to The Moov Authors under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. The Moov Authors licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package iso3166

var alpha3Codes = map[string][]string{
	"ABW": {"Aruba"},
	"AFG": {"Afghanistan"},
	"AGO": {"Angola"},
	"AIA": {"Anguilla"},
	"ALA": {"Åland Islands"},
	"ALB": {"Albania"},
	"AND": {"Andorra"},
	"ARE": alpha2Codes["AE"],
	"ARG": {"Argentina"},
	"ARM": {"Armenia"},
	"ASM": {"American Samoa"},
	"ATA": {"Antarctica"},
	"ATF": {"French Southern Territories"},
	"ATG": {"Antigua and Barbuda"},
	"AUS": {"Australia"},
	"AUT": {"Austria"},
	"AZE": {"Azerbaijan"},
	"BDI": {"Burundi"},
	"BEL": {"Belgium"},
	"BEN": {"Benin"},
	"BES": alpha2Codes["BQ"],
	"BFA": {"Burkina Faso"},
	"BGD": {"Bangladesh"},
	"BGR": {"Bulgaria"},
	"BHR": {"Bahrain"},
	"BHS": {"Bahamas"},
	"BIH": {"Bosnia and Herzegovina"},
	"BLM": alpha2Codes["BL"],
	"BLR": {"Belarus"},
	"BLZ": {"Belize"},
	"BMU": {"Bermuda"},
	"BOL": alpha2Codes["BO"],
	"BRA": {"Brazil"},
	"BRB": {"Barbados"},
	"BRN": alpha2Codes["BN"],
	"BTN": {"Bhutan"},
	"BVT": {"Bouvet Island"},
	"BWA": {"Botswana"},
	"CAF": alpha2Codes["CF"],
	"CAN": {"Canada"},
	"CCK": alpha2Codes["CC"],
	"CHE": {"Switzerland"},
	"CHL": {"Chile"},
	"CHN": alpha2Codes["CN"],
	"CIV": alpha2Codes["CI"],
	"CMR": {"Cameroon"},
	"COD": alpha2Codes["CD"],
	"COG": alpha2Codes["CG"],
	"COK": {"Cook Islands"},
	"COL": {"Colombia"},
	"COM": {"Comoros"},
	"CPV": alpha2Codes["CV"],
	"CRI": {"Costa Rica"},
	"CUB": {"Cuba"},
	"CUW": {"Curaçao"},
	"CXR": {"Christmas Island"},
	"CYM": {"Cayman Islands"},
	"CYP": {"Cyprus"},
	"CZE": alpha2Codes["CZ"],
	"DEU": {"Germany"},
	"DJI": {"Djibouti"},
	"DMA": {"Dominica"},
	"DNK": {"Denmark"},
	"DOM": {"Dominican Republic"},
	"DZA": {"Algeria"},
	"ECU": {"Ecuador"},
	"EGY": {"Egypt"},
	"ERI": {"Eritrea"},
	"ESH": {"Western Sahara"},
	"ESP": {"Spain"},
	"EST": {"Estonia"},
	"ETH": {"Ethiopia"},
	"FIN": {"Finland"},
	"FJI": {"Fiji"},
	"FLK": alpha2Codes["FK"],
	"FRA": {"France"},
	"FRO": {"Faroe Islands"},
	"FSM": alpha2Codes["FM"],
	"GAB": {"Gabon"},
	"GBR": alpha2Codes["GB"],
	"GEO": {"Georgia"},
	"GGY": {"Guernsey"},
	"GHA": {"Ghana"},
	"GIB": {"Gibraltar"},
	"GIN": {"Guinea"},
	"GLP": {"Guadeloupe"},
	"GMB": {"Gambia"},
	"GNB": alpha2Codes["GW"],
	"GNQ": {"Equatorial Guinea"},
	"GRC": {"Greece"},
	"GRD": {"Grenada"},
	"GRL": {"Greenland"},
	"GTM": {"Guatemala"},
	"GUF": {"French Guiana"},
	"GUM": {"Guam"},
	"GUY": {"Guyana"},
	"HKG": {"Hong Kong"},
	"HMD": {"Heard Island and McDonald Islands"},
	"HND": {"Honduras"},
	"HRV": {"Croatia"},
	"HTI": {"Haiti"},
	"HUN": {"Hungary"},
	"IDN": {"Indonesia"},
	"IMN": {"Isle of Man"},
	"IND": {"India"},
	"IOT": {"British Indian Ocean Territory"},
	"IRL": {"Ireland"},
	"IRN": alpha2Codes["IR"],
	"IRQ": {"Iraq"},
	"ISL": {"Iceland"},
	"ISR": {"Israel"},
	"ITA": {"Italy"},
	"JAM": {"Jamaica"},
	"JEY": {"Jersey"},
	"JOR": {"Jordan"},
	"JPN": {"Japan"},
	"KAZ": {"Kazakhstan"},
	"KEN": {"Kenya"},
	"KGZ": {"Kyrgyzstan"},
	"KHM": {"Cambodia"},
	"KIR": {"Kiribati"},
	"KNA": {"Saint Kitts and Nevis"},
	"KOR": alpha2Codes["KR"],
	"KWT": {"Kuwait"},
	"LAO": alpha2Codes["LA"],
	"LBN": {"Lebanon"},
	"LBR": {"Liberia"},
	"LBY": {"Libya"},
	"LCA": {"Saint Lucia"},
	"LIE": {"Liechtenstein"},
	"LKA": {"Sri Lanka"},
	"LSO": {"Lesotho"},
	"LTU": {"Lithuania"},
	"LUX": {"Luxembourg"},
	"LVA": {"Latvia"},
	"MAC": alpha2Codes["MO"],
	"MAF": alpha2Codes["MF"],
	"MAR": {"Morocco"},
	"MCO": {"Monaco"},
	"MDA": alpha2Codes["MD"],
	"MDG": {"Madagascar"},
	"MDV": {"Maldives"},
	"MEX": {"Mexico"},
	"MHL": {"Marshall Islands"},
	"MKD": alpha2Codes["MK"],
	"MLI": {"Mali"},
	"MLT": {"Malta"},
	"MMR": alpha2Codes["MM"],
	"MNE": {"Montenegro"},
	"MNG": {"Mongolia"},
	"MNP": alpha2Codes["MP"],
	"MOZ": {"Mozambique"},
	"MRT": {"Mauritania"},
	"MSR": {"Montserrat"},
	"MTQ": {"Martinique"},
	"MUS": {"Mauritius"},
	"MWI": {"Malawi"},
	"MYS": {"Malaysia"},
	"MYT": {"Mayotte"},
	"NAM": {"Namibia"},
	"NCL": {"New Caledonia"},
	"NER": {"Niger"},
	"NFK": {"Norfolk Island"},
	"NGA": {"Nigeria"},
	"NIC": {"Nicaragua"},
	"NIU": {"Niue"},
	"NLD": alpha2Codes["NL"],
	"NOR": {"Norway"},
	"NPL": {"Nepal"},
	"NRU": {"Nauru"},
	"NZL": alpha2Codes["NZ"],
	"OMN": {"Oman"},
	"PAK": {"Pakistan"},
	"PAN": {"Panama"},
	"PCN": {"Pitcairn"},
	"PER": {"Peru"},
	"PHL": {"Philippines"},
	"PLW": {"Palau"},
	"PNG": alpha2Codes["PG"],
	"POL": {"Poland"},
	"PRI": {"Puerto Rico"},
	"PRK": alpha2Codes["KP"],
	"PRT": {"Portugal"},
	"PRY": {"Paraguay"},
	"PSE": alpha2Codes["PS"],
	"PYF": {"French Polynesia"},
	"QAT": {"Qatar"},
	"REU": alpha2Codes["RE"],
	"ROU": {"Romania"},
	"RUS": alpha2Codes["RU"],
	"RWA": {"Rwanda"},
	"SAU": alpha2Codes["SA"],
	"SDN": {"Sudan"},
	"SEN": {"Senegal"},
	"SGP": {"Singapore"},
	"SGS": {"South Georgia and the South Sandwich Islands"},
	"SHN": alpha2Codes["SH"],
	"SJM": {"Svalbard and Jan Mayen"},
	"SLB": {"Solomon Islands"},
	"SLE": {"Sierra Leone"},
	"SLV": {"El Salvador"},
	"SMR": {"San Marino"},
	"SOM": {"Somalia"},
	"SPM": {"Saint Pierre and Miquelon"},
	"SRB": {"Serbia"},
	"SSD": {"South Sudan"},
	"STP": {"Sao Tome and Principe"},
	"SUR": {"Suriname"},
	"SVK": {"Slovakia"},
	"SVN": {"Slovenia"},
	"SWE": {"Sweden"},
	"SWZ": alpha2Codes["SZ"],
	"SXM": alpha2Codes["SX"],
	"SYC": {"Seychelles"},
	"SYR": alpha2Codes["SY"],
	"TCA": {"Turks and Caicos Islands"},
	"TCD": {"Chad"},
	"TGO": {"Togo"},
	"THA": alpha2Codes["TH"],
	"TJK": {"Tajikistan"},
	"TKL": {"Tokelau"},
	"TKM": {"Turkmenistan"},
	"TLS": alpha2Codes["TL"],
	"TON": {"Tonga"},
	"TTO": {"Trinidad and Tobago"},
	"TUN": {"Tunisia"},
	"TUR": alpha2Codes["TR"],
	"TUV": {"Tuvalu"},
	"TWN": alpha2Codes["TW"],
	"TZA": alpha2Codes["TZ"],
	"UGA": {"Uganda"},
	"UKR": {"Ukraine"},
	"UMI": alpha2Codes["UM"],
	"URY": {"Uruguay"},
	"USA": alpha2Codes["US"],
	"UZB": {"Uzbekistan"},
	"VAT": alpha2Codes["VA"],
	"VCT": {"Saint Vincent and the Grenadines"},
	"VEN": alpha2Codes["VE"],
	"VGB": alpha2Codes["VG"],
	"VIR": alpha2Codes["VI"],
	"VNM": alpha2Codes["VN"],
	"VUT": {"Vanuatu"},
	"WLF": {"Wallis and Futuna"},
	"WSM": {"Samoa"},
	"YEM": {"Yemen"},
	"ZAF": {"South Africa"},
	"ZMB": {"Zambia"},
	"ZWE": {"Zimbabwe"},
}
